### ISSUE TITLE
Issue with npm package

### ISSUE THREAD

**Issue by amgadfahmi** [stephanebachelier/generator-jslib#3]
Thanks for the generator, am facing an issue with the output to work with npm as when i did testing for the package as here https://tonicdev.com/npm/js-binarysearch its says object is undefined. 
The project output is here https://github.com/amgadfahmi/js-binarysearch/blob/master/dist/js-binarysearch.js

Am not an npm expert but did I miss anything !

**Comment by stephanebachelier** [comment]
@amgadfahmi I'll close the issue as it seems to work on tonicdev. 
I didn't know about this project, really helpful :)
